# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Matematiikkakilpailut
tagline: Suomen matematiikan olympiavalmennus
author :
  name : Suomen matemaattisen yhdistyksen valmennusjaos
  github : matematiikkakilpailut

production_url : http://matematiikkakilpailut.fi
url: http://matematiikkakilpailut.fi
  
plugins:
  - jekyll-sitemap

seiskat_pages:
  - { fi: "ohjeet"     , sv: "regler"    , en: "details" }
  - { fi: "jarjestajat", sv: "arrangorer", en: "organizers" }
  - { fi: "tehtavat"   , sv: "problem"   , en: "problems" }
  - { fi: "tulokset"   , sv: "resultat"  , en: "results" }
  - { fi: "yhteys"     , sv: "kontakt"   , en: "contact" }
  - { fi: "index"      , sv: "index"     , en: "index" }

seiskat_menu:
  fi: "Valikko"
  sv: "Meny"
  en: "Menu"
  
defaults:
  - scope:
      path: "valmennus/20*/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "seiskat/*"
    values:
      layout: "seiskat"
      title: "Seitsemäsluokkalaisten kilpailu"
      h1: "7. luokkalaisten alueellinen matematiikkakilpailu"
      lang: "fi"
  - scope:
      path: "seiskat/sv/*"
    values:
      layout: "seiskat"
      title: "Sjunde klassens tävling"
      h1: "Matematiktävling för elever på 7:e årsklassen"
      lang: "sv-FI"
  - scope:
      path: "seiskat/en/*"
    values:
      layout: "seiskat"
      title: "7th Graders' Competition"
      h1: "7th Graders' Regional Mathematics Competition"
      lang: "en"
  - scope:
      path: "matkalasku"
    values:
      sitemap: false
